### ISSUE TITLE
Elasticsearch 8 / Opensearch

### ISSUE THREAD

**Issue by btxtiger** [FriendsOfShopware/FroshTools#195]
### PHP Version

8.2

### Shopware Version

6.4.20.1

### Actual behaviour

When switching to the Docker image `elasticsearch:8.7.1` or `opensearchproject/opensearch:latest` the frontend just shows "Elastic search not enabled." 

While using `elasticsearch:7.17.10`, everything works fine.

### Expected behaviour

Should show the ES dashboard

### Steps to Reproduce?

Docker compose service:

```yaml
    elasticsearch:
        image: elasticsearch:7.17.10
        container_name: shopware_elasticsearch_PROD
        restart: unless-stopped
        environment:
            ES_JAVA_OPTS: -Xms512m -Xmx512m
            discovery.type: single-node
        networks:
            - web
```

Just replace the image tag and run `docker compose up -d --force-recreate elasticsearch`
